config/routes.rb
Rails.application.routes.draw do

  root to: "items#index"
  # get 'items/new'
  # get 'items/create'
  # get 'items/show'
  # get 'items/edit'
  # get 'items/update'
  # get 'items/destroy'
  resources :users, except: [ :index ]

  # get 'session/new'
  # get 'session/create'
  # get 'session/destroy'
  # get 'users/new'
  # get 'users/create'
  # get 'users/show'
  # get 'users/edit'
  # get 'users/update'
  # get 'users/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Session routes for login/logut
get    "/login" => "session#new"     # login form
post   "/login" => "session#create"  # form submits here to perform login and set session
delete "/login" => "session#destroy" # logout (delete session)

get "/app" => "items#app"

resources :items

#post "items/search" => "items#search", as: 'search_items'

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password   # makes 'password' field MANDATORY
  validates :email, presence: true, uniqueness: true
  has_many :items
  before_save { self.email = email.downcase }
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
      @user = User.create user_params   # strong params

      if @user.persisted?
        # Account created successfully!
        session[:user_id] = @user.id   # Log in the new user!!
        #added next 4 lines for Cloudinary image upload
        if params[:file].present?
          response= Cloudinary::Uploader.upload params[:file]
          @user.image = response["public_id"]
          @user.save
        end
        redirect_to user_path(@user)   # go to the show page for this user
      else
        # Account not created: show error

        # Set a flash key to show on the next page: it will be an array of error strings
        flash[:errors] = @user.errors.full_messages
        redirect_to new_user_path  # /users/new, show the form again (with errors)
      end
  end

  def show
    @user = User.find params[:id]

  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find params[:id]
    redirect_to root_path unless @user.id == @current_user.id
  end

  def update

    @user = User.find params[:id]   # route is PATCH "/members/:id", so we have the ID in params


    @user.update user_params
    if params[:file].present?
      response= Cloudinary::Uploader.upload params[:file]
      @user.image = response["public_id"]
      @user.save
    end
    redirect_to user_path(@user.id)

  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    redirect_to( root_path )
  end

  private
  # strong params, the doorman for the form fields
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if flash[:errors].present?  %>
   <strong>Please correct the following errors:</strong>
   <ol>
   <% flash[:errors].each do |error| %>
     <li><%= error %></li>
   <% end %>
   </ol>
<% end %>

<%= form_for @user, html: {multipart: true} do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.label :image %>
  <%= f.cl_image_upload :image %>
  <br>

  <%= f.submit %>

<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h2>Create an Account</h2>
<%= render partial: 'form' %>

app/views/users/show.html.erb
<div>
<h2><%= @user.name %></h2>

<div>
  <%= link_to 'Edit Account', edit_user_path(@user) %>
  |
  <%= link_to 'New Item', new_item_path %>
  |
  <%= link_to 'Delete Account', user_path(@user), method: 'delete' %>
</div>
<br>

<div class='userLst'>
<strong>Name:</strong> <%= @user.name %><br>

<%= cl_image_tag @user.image, alt: @user.name, class: 'avartar img-responsive img-thumbnail pull-left' %>

<h3>   Your Listing</h3>
  <ul>
  <% @user.items.each do |item| %>
    <li>
      <%= link_to item.summary, item_path(item.id) %>
    </li>
  <% end %>
  </ul>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>