config/routes.rb
Rails.application.routes.draw do

  root to: "items#index"
  # get 'items/new'
  # get 'items/create'
  # get 'items/show'
  # get 'items/edit'
  # get 'items/update'
  # get 'items/destroy'
  resources :users, except: [ :index ]

  # get 'session/new'
  # get 'session/create'
  # get 'session/destroy'
  # get 'users/new'
  # get 'users/create'
  # get 'users/show'
  # get 'users/edit'
  # get 'users/update'
  # get 'users/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Session routes for login/logut
get    "/login" => "session#new"     # login form
post   "/login" => "session#create"  # form submits here to perform login and set session
delete "/login" => "session#destroy" # logout (delete session)

get "/app" => "items#app"

resources :items

#post "items/search" => "items#search", as: 'search_items'

end

app/models/item.rb
class Item < ApplicationRecord

belongs_to :category, optional:true
belongs_to :user, optional:true
validates :summary, presence: true
# GeoCode
geocoded_by :address
after_validation :geocode
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def app
    # raise 'hell'
  end

  # CREATE
  def new
        @item = Item.new   # create a blank object for the form_for helper to use
  end

  def create
    # Multi-step way to create a new Post record in the database
    # for when we have to add some data that is not in the submitted
    # form (i.e., the user ID from the currently logged-in user):
    # First make a .new object, set the extra field, then .save
    @item = Item.new( item_params )  # strong params
    @item.user = @current_user
    # raise "hell"

      if params[:file].present?
          response = Cloudinary::Uploader.upload params[:file]
          @item.item_image = response["public_id"]
          @item.save
      end
    #@item.save
    if @item.persisted?
      #raise('hell')
      redirect_to items_path # redirect to index
    else
      # @post did not get saved to the DB
      flash[:errors] = @item.errors.full_messages # an array of error strings we can print
      # redirect_to new_item_path
      # Render a *different* action's template (new instead of create)
      # We do this so the form can be pre-populated with the values typed
      # in by the user when they submitted it the first time
      render :new
    end
  end

  # READ
  def index

    if params[:search_form].present?

      # either search by address, or search by current location
      if params[:use_geolocation]
        location = [ params[:latitude].to_f, params[:longitude].to_f  ]
      else
        location = params[:search]
      end

      #@items = Item.near(params[:search], 10,:units=>:km, :order => :distance)
      @items = Item.near(location, 10, :units=>:km)

    else
      # Not a search - show all items

      @items = Item.all.order('created_at DESC')

      # handle both HTML and JSON requests
      respond_to do |format|
        format.html
        format.json { render json: @items  }
      end

    end

  end

  def show
    @item = Item.find params[:id]
    @whereLat = (@item.latitude)
    @whereLng = (@item.longitude)

    respond_to do |format|
      format.html
      format.json { render json: @item  }
    end

  end

  # UPDATE
  def edit
    @item = Item.find params[:id]
  end

  def update
    @item = Item.find params[:id]  # key comes from /posts/:id
    # Check that the owner of this item is STILL the logged-in user
    # (i.e. the ID in the edit form action was not tampered with)
    unless @item.user == @current_user
      redirect_to(root_path) # this alone does not stop the action
    return  # stop the rest of the action from running! i.e. the update below
    end
    # check whether the update actually changed the DB or not
    # (.update returns true if it did change the DB, false if there was an error)
    if @item.update( item_params )
      if params[:file].present?
          response= Cloudinary::Uploader.upload params[:file]
          @item.item_image = response["public_id"]
          @item.save
      end
      # successfully updated the DB
      redirect_to item_path(@item) # redirect to show page
    else
      # error updating
      flash[:errors] = @item.errors.full_messages
      render :edit   # Render the edit template to show the form, even though this is the update action
    end
  end

  # DESTROY
  def destroy
    @item = Item.find params[:id]
    @item.destroy
    redirect_to( items_path )
  end
  private

    #Security for the the CREATE and UPDATE
    def item_params
        params.require(:item).permit(:summary, :description, :item_image, :qty, :address, :category_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<% if flash[:errors].present?  %>
   <strong>Please correct the following errors:</strong>
   <ol>
   <% flash[:errors].each do |error| %>
     <li><%= error %></li>
     <br>
     <br>
     <br>
   <% end %>
   </ol>
<% end %>

<%= form_for @item, html: {multipart: true} do |f| %>
  <p>
  <%= f.label :summary %><br>
  <%= f.text_field :summary, size: 52 %>
  </p>
  <p>
  <%= f.label :description %><br>
  <%= f.text_area :description,cols: 50, rows: 10 %>
  </p>
  <p>
   <%= f.label :item_image, 'Item Image'  %><br>
   <%= f.cl_image_upload :item_image %>
  </p>
  <p>
   <%= f.label :qty %><br>
   <%= f.number_field :qty %>
  </p>

  <p>
  <%= f.label :category_id, 'Category' %>
  <%= f.collection_select :category_id, Category.all, :id, :name, prompt: 'Please choose or edit a category:' %>
  </p>
  <p>
  <%= f.label :address %><br>
  <%= f.text_field :address %>
  </p>
  <p>
  <%= f.submit 'Submit', :class => 'button'%>
  </p>

<% end %>

app/views/items/app.html.erb
<%= javascript_pack_tag 'application' %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<h2>Edit Listing</h2>
<%= link_to 'Delete Item' , item_path(@item), method: 'delete'%>
<%= render partial: 'form' %>

app/views/items/index.html.erb
<div>
<h2>Items</h2>
<ul>
  <% @items.each do |item| %>
  <li>
    <a href="<%= item_path(item.id) %>">
    <%= item.summary %>(<%= item.category.name %>)

    </a>
  </li>
<% end %>
</ul>
</div>

app/views/items/new.html.erb
<h2>Create Item</h2>

<%= render partial: 'form' %>

app/views/items/show.html.erb
<% if flash[:errors].present?  %>
   <strong>Please correct the following errors:</strong>
   <ol>
   <% flash[:errors].each do |error| %>
     <li><%= error %></li>
   <% end %>
   </ol>
<% end %>

<!--  -->
<div class='container'>
<div class="row">
  <div class="col-md-12">
    <h2><%= @item.summary %>(Qty:<%= @item.qty %>)</h2>
    <h2>(<%= @item.address %>)</h2>
    <br>
    <h4 class="itemDesc"><%= @item.description %></h4>
  </div>
</div>
</div>

<hr>
<div>
<% if @item.item_image.present? %>
<%= cl_image_tag @item.item_image, class: 'postTitle' %>
<% end %>
</div>
<br>
<hr>

<!--The div element for the map -->
<div id="map">
</div>
<script>

function initMap() {

  // var itemLoc = {lat: -33.8119855, lng: 151.1827005};
  var itemLoc = {lat: <%= @item.latitude %>, lng: <%= @item.longitude %>};
  console.log(itemLoc)
  // The map
  var map = new google.maps.Map(
      document.getElementById('map'), {zoom: 12, center: itemLoc});
  // The marker.
  var marker = new google.maps.Marker({position: itemLoc, map: map});
}
</script>

<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBwRD1Tg7-nm-4XPH8zXZzGV2Jf8pwQywE&callback=initMap">
</script>

<!--Only show if it belong to user.  -->
<% if @current_user.present? && @item.user == @current_user  %>
<%= link_to 'Edit Item', edit_item_path(@item) %>
|
<%= link_to 'Email', edit_item_path(@item) %>

<% end  %>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>