config/routes.rb
Rails.application.routes.draw do

  root to: "items#index"
  # get 'items/new'
  # get 'items/create'
  # get 'items/show'
  # get 'items/edit'
  # get 'items/update'
  # get 'items/destroy'
  resources :users, except: [ :index ]

  # get 'session/new'
  # get 'session/create'
  # get 'session/destroy'
  # get 'users/new'
  # get 'users/create'
  # get 'users/show'
  # get 'users/edit'
  # get 'users/update'
  # get 'users/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Session routes for login/logut
get    "/login" => "session#new"     # login form
post   "/login" => "session#create"  # form submits here to perform login and set session
delete "/login" => "session#destroy" # logout (delete session)

get "/app" => "items#app"

resources :items

#post "items/search" => "items#search", as: 'search_items'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FarmShare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= cloudinary_js_config %>

  </head>

  <body>

    <a href="<%= root_path %>"><h1 class="mainHead">FarmShare</h1></a>
    <br>
    <nav>
    <div class="searchItem">
    <%= form_tag items_path, :method => :get do %>
    <p>
    <%= text_field_tag :search, params[:search] %>
    <br>
    OR
    <br>
    <input type="checkbox" name="use_geolocation" value="true"> Use Current Location
    <br>
    <!-- within
    <select name="radius" id="radius">
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="5">5</option>
      <option value="10">10</option>
      <option value="20">20</option>
      <option value="50">50</option>
    </select>
    of current location -->
    <%= submit_tag "Search Near" ,:class=>"button",:name => nil %>
    </p>
    <input type="hidden" name="latitude" value="" id="lat"  />
    <input type="hidden" name="longitude" value="" id="lng" />
    <input type="hidden" name="search_form" value="true"  />
    <% end %>
    </div>

  <script>

    var options = {
      enableHighAccuracy: true,
      timeout: 5000,
      maximumAge: 0
    };

    let lat;
    let lng;

    function success(pos) {
      var crd = pos.coords;

      //console.log('Your current position is:');
      //console.log(`Latitude : ${crd.latitude}`);
      //console.log(`Longitude: ${crd.longitude}`);
      //console.log(`More or less ${crd.accuracy} meters.`);

      position = {lat: crd.latitude, lng: crd.longitude}
      //console.log(position);

      // set the coordinates into the hidden form fields to submit to Rails
      document.getElementById('lat').value = crd.latitude;
      document.getElementById('lng').value = crd.longitude;

      return position;
    }

    function error(err) {
      console.warn(`ERROR(${erdcr.code}): ${err.message}`);
    }

    navigator.geolocation.getCurrentPosition(success, error, options);
  </script>

      <% if @current_user.present? %>
        <h2>Welcome, <%= @current_user.name %> </h2>

         <%= link_to 'Home ', items_path %>
        |
        <%= link_to 'Logout', login_path, method: 'delete' %>
        |
        <%= link_to 'View Items', items_path %>
        |
        <%= link_to 'My Account', user_path(@current_user) %>
      <% else %>
        <%= link_to 'Login', login_path %>
        |
        <%= link_to 'Sign up', new_user_path %>
      <% end %>
    </nav>
    <hr>
    <%= yield %>
  </body>
</html>